import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input:
      'https://raw.githubusercontent.com/airbytehq/airbyte/v0.39.37-alpha/airbyte-api/src/main/openapi/config.yaml',
    output: {
      target: './src/generated/AirbyteApi.ts',
      prettier: true,
      mode: 'split',
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval`,
          `Do not edit manually. Run "npm run generate-client" instead.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        mutator: {
          path: './src/orval/override.ts',
          name: 'apiOverride',
        },
      },
    },
  },
});
